version: '3.1'

services:
  db:
    image: postgres:15
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: isbnd
      POSTGRES_PASSWORD: isbn4152
      POSTGRES_DB: celulas
    volumes:
      - ms-celulas:/var/lib/postgresql

volumes:
  ms-celulas:
